services:
  client:
    image: anselchang1/nestris.org:client-${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "80:80"  # Expose port 80 for production
    depends_on:
      - server  # Ensure client waits for server to be ready
    command: >
      sh -c "nginx -g 'daemon off;';"

  server:
    image: anselchang1/nestris.org:server-${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
